### ISSUE TITLE
Wrong instrument in generated file

### ISSUE THREAD

**Issue by Mathieu-Schalkwijk** [TobiasBonifay/dsl-midi_MusicDSL#51]
#44 
When putting synth1 track after drum tracks, synth1 becomes a basic piano in the output file.
When putting synth1 track after after synth2 track, synth2 instrument becomes synth1 instrument.

**Comment by TobiasBonifay** [comment]
Midi Channel issue + Drum should probably manage all tracks on 10 using a specific processing. I'm on it.
